---
- name: enable cassandra
  command: /sbin/chkconfig cassandra on
  when: cassandra22x_cassandra_enable_safe == true

- name: start cassandra service
  command: systemctl start cassandra
  notify: start cassandra service nodetool status
  when: cassandra22x_cassandra_enable_safe == true and 
         cassandra22x_cassandra_restart_safe == true  

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
