---
- name: install authenticator configuration
  lineinfile:
    path: "{{ cassandra22x_yaml }}"
    owner: "{{ cassandra22x_linux_user }}"
    group: "{{ cassandra22x_linux_group }}"
    mode: "{{ cassandra22x_cassandra_conf_file_mode }}"
    regexp: "{{ cassandra22x_authenticator_replace_configuration }}"
    line: "{{ cassandra22x_authenticator_configuration }}"
    state: present
  notify: 
    - nodetool drain restart cassandra
    - nodetool stopdaemon restart cassandra    
    - stop cassandra service restart cassandra
    - start cassandra service  restart cassandra
    - nodetool statusbinary restart cassandra
    - nodetool statusgossip restart cassandra
    - nodetool statushandoff restart cassandra
    - create default cql users
