---
# ansible-playbook /etc/ansible/playbooks/cassandra22x/role_provisioning_cassandra22x_enable_start.yml --extra-vars "target=ansible_inventory_hosts"
- hosts: "{{ target | default('FAIL') }}"
  gather_facts: true
  any_errors_fatal: true
  serial: 1
  roles:
    - cassandra22x_provision_enable_start
