---
- name: install jmxremote.password
  template:
    src: jmxremote.password
    dest: "{{ cassandra22x_jmxremote_password }}"
    owner: "{{ cassandra22x_linux_user }}"
    group: "{{ cassandra22x_linux_group }}"    
    mode: "{{ cassandra22x_cassandra_sec_file_mode }}"
