---
- name: start cassandra service nodetool status
  command: "nodetool -u {{ cassandra22x_remote_jmx_user }} -pw {{ cassandra22x_remote_jmx_pass}} status"
  register: statushandoff
  until: statushandoff.stdout.find("UJ") != 1 and statushandoff.stdout.find("UN") != -1
  retries: 10
  delay: 6
  ignore_errors: yes
